url: https://schleise-girls-imperium.de/
baseurl: ""

# Site settings
title: Schleise Girls
email: schleisesabine@gmail.com
description: "SGI - Marion, Nelly, Sabine"

# Team names, titles and social links
people:
- name: Nelly Schleise
  pic: 1
  position: Organisational Manager
  social:
    - title: instagram
      url: #
    - title: linkedin
      url: #

- name: Marion Schleise
  pic: 2
  position: Financial Manager
  social:
    - title: instagram
      url: #
    - title: youtube
      url: #
    - title: linkedin
      url: #

- name: Sabine Schleise
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #
    - title: github
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty